# Generated by Django 3.2.4 on 2021-07-25 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_user_watchlist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bid',
            options={'ordering': ['id', '-amount']},
        ),
        migrations.RemoveField(
            model_name='listing',
            name='highest_bid',
        ),
        migrations.AddField(
            model_name='bid',
            name='listing',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='auctions.listing'),
            preserve_default=False,
        ),
    ]
