# Generated by Django 3.2.4 on 2021-07-25 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20210725_1607'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bid',
            options={'ordering': ['id', 'amount']},
        ),
    ]
